jobs:
  - name: aws-clive-dev
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: aws-clive
            trigger: true
          - get: emr-launcher-release
            trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
