jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            CORRELATION_ID: test
            SNAPSHOT_TYPE: "full"
            EXPORT_DATE: "2021-05-06"
            S3_PREFIX: analytical-dataset/full/2021-05-06_10-28-04/
