jobs:
  - name: aws-clive-qa
    max_in_flight: 1
    plan:
      - get: aws-clive
        trigger: true
        passed:
          - aws-clive-dev
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
