jobs:
  - name: aws-clive-prod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-clive
            trigger: true
            passed:
              - aws-clive-preprod
          - get: emr-launcher-release
            trigger: true
          - get: emr-al2-ami
            trigger: true
            passed:
            - aws-clive-preprod
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: production
